config/routes.rb
require 'api_constraints'
ParkNGo::Application.routes.draw do

  resources :services


  resources :prices


  resources :transactions


  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        resources :bookings
        resources :feedbacks
        resources :parking_types
        resources :parkings
        resources :parking_companies
        resources :parking_branches
        resources :cars
    end
  end

  resources :cars


  match '/bookings/current', to: 'bookings#current', :as => "current_bookings"

  # get "parking_companies/new"
  match '/company/add', to: 'parking_companies#new', :as => "add_parking_company"
  # get "parking_branch/new"
  match '/company/branch/add', to: 'parking_branches#new', :as => "add_parking_branch"
   # get "parking_branch/show"
  match '/company/branch/:id', to: 'parking_branches#show', :as => "show_company_branch"
    # get "edit_parking_company" => parking_companies#edit custom route edit_parking_company_path
  match '/company/edit/:id', to: 'parking_companies#edit', :as => "edit_parking_company"
  # get "parking_companies/index" custom route all_companies_path 
  match '/company', to: 'parking_companies#index', :as => "all_companies" 

  match '/company/show' => redirect('/company')
  # match '/parking_companies' => redirect('/company')


  # branch_by_airport_path(:airport)
  match '/airport/:airport', to: 'parking_branches#index', :as => "branch_by_airport" 

  get "parking_companies/destroy"

  get "parking_branches/index"

  get "parking_branches/update"

  get "parking_branches/destroy"


  # get "parking_companies/show" custom route show_company_path

  match '/company/show/:company_name', to: 'parking_companies#show', :as => "show_company"
  # match '/parking_companies/:id' => redirect('/company/show/%{id}')
  # match '/company/show/:id', to: 'parking_companies#show', :as => "show_company_by_id"
  match '/company/branch' => redirect('/company')
  match '/company/:company_name', to: 'parking_companies#index', :as => "company_by_name" 
  
  # get "parking_companies/update"
  # match '/company/update', to: 'parking_companies#update', :as => ""





 
  


  #pass the id to path edit_parking_branch_path(id)
  match '/company/branch/edit/:id', to: 'parking_branches#edit', :as => "edit_parking_branch"
  



  authenticated :user do
    root :to => 'home#index'
    
  end
  root :to => "home#index"

  devise_for :users, :path_names => { :sign_up => "register" }, :path_names => { :sign_in => "login" }
  resources :users do
    resources :addreses
  end

  resources :bookings


  resources :feedbacks


  resources :parking_types


  resources :parkings
  resources :parking_companies
  resources :parking_branches




end

app/models/price.rb
class Price < ActiveRecord::Base
  attr_accessible :service_id, :parking_id, :price_amount, :price_currency, :base_price, :duration, :price_rule
  belongs_to :parking
  belongs_to :service
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
  # GET /prices
  # GET /prices.json
  def index
    @prices = Price.all
  end

  # GET /prices/1
  # GET /prices/1.json
  def show
    @price = Price.find(params[:id])
  end

  # GET /prices/new
  # GET /prices/new.json
  def new
    @price = Price.new
  end

  # GET /prices/1/edit
  def edit
    @price = Price.find(params[:id])
  end

  # POST /prices
  # POST /prices.json
  def create
    @price = Price.new(params[:price])

      if @price.save
        redirect_to @price, notice: 'Price was successfully created.'
      else
        render action: "new"
      end
  end

  # PUT /prices/1
  # PUT /prices/1.json
  def update
    @price = Price.find(params[:id])

      if @price.update_attributes(params[:price])
        redirect_to @price, notice: 'Price was successfully updated.'
      else
        render action: "edit"
      end
  end

  # DELETE /prices/1
  # DELETE /prices/1.json
  def destroy
    @price = Price.find(params[:id])
    @price.destroy
  end
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<%= semantic_form_for @price do |f| %>
  <%= f.inputs  %>
  <%#= f.input :service_id %>
  <%#= f.input :parking_id %>
  <%# end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/prices/edit.html.erb
<h1>Editing price</h1>

<%= render 'form' %>

<%= link_to 'Show', @price %> |
<%= link_to 'Back', prices_path %>

app/views/prices/index.html.erb
<h1>Listing prices</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prices.each do |price| %>
  <tr>
    <td><%= link_to 'Show', price %></td>
    <td><%= link_to 'Edit', edit_price_path(price) %></td>
    <td><%= link_to 'Destroy', price, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Price', new_price_path %>

app/views/prices/new.html.erb
<h1>New price</h1>

<%= render 'form' %>

<%= link_to 'Back', prices_path %>

app/views/prices/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_price_path(@price) %> |
<%= link_to 'Back', prices_path %>