config/routes.rb
require 'api_constraints'
ParkNGo::Application.routes.draw do

  resources :services


  resources :prices


  resources :transactions


  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        resources :bookings
        resources :feedbacks
        resources :parking_types
        resources :parkings
        resources :parking_companies
        resources :parking_branches
        resources :cars
    end
  end

  resources :cars


  match '/bookings/current', to: 'bookings#current', :as => "current_bookings"

  # get "parking_companies/new"
  match '/company/add', to: 'parking_companies#new', :as => "add_parking_company"
  # get "parking_branch/new"
  match '/company/branch/add', to: 'parking_branches#new', :as => "add_parking_branch"
   # get "parking_branch/show"
  match '/company/branch/:id', to: 'parking_branches#show', :as => "show_company_branch"
    # get "edit_parking_company" => parking_companies#edit custom route edit_parking_company_path
  match '/company/edit/:id', to: 'parking_companies#edit', :as => "edit_parking_company"
  # get "parking_companies/index" custom route all_companies_path 
  match '/company', to: 'parking_companies#index', :as => "all_companies" 

  match '/company/show' => redirect('/company')
  # match '/parking_companies' => redirect('/company')


  # branch_by_airport_path(:airport)
  match '/airport/:airport', to: 'parking_branches#index', :as => "branch_by_airport" 

  get "parking_companies/destroy"

  get "parking_branches/index"

  get "parking_branches/update"

  get "parking_branches/destroy"


  # get "parking_companies/show" custom route show_company_path

  match '/company/show/:company_name', to: 'parking_companies#show', :as => "show_company"
  # match '/parking_companies/:id' => redirect('/company/show/%{id}')
  # match '/company/show/:id', to: 'parking_companies#show', :as => "show_company_by_id"
  match '/company/branch' => redirect('/company')
  match '/company/:company_name', to: 'parking_companies#index', :as => "company_by_name" 
  
  # get "parking_companies/update"
  # match '/company/update', to: 'parking_companies#update', :as => ""





 
  


  #pass the id to path edit_parking_branch_path(id)
  match '/company/branch/edit/:id', to: 'parking_branches#edit', :as => "edit_parking_branch"
  



  authenticated :user do
    root :to => 'home#index'
    
  end
  root :to => "home#index"

  devise_for :users, :path_names => { :sign_up => "register" }, :path_names => { :sign_in => "login" }
  resources :users do
    resources :addreses
  end

  resources :bookings


  resources :feedbacks


  resources :parking_types


  resources :parkings
  resources :parking_companies
  resources :parking_branches




end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :comment, :feedback_id, :raiting, :booking_id
  belongs_to :booking
end

app/controllers/api/v1/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @feedbacks }
    end
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/new
  # GET /feedbacks/new.json
  def new
    @feedback = Feedback.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @feedback }
    end
  end

  # GET /feedbacks/1/edit
  def edit
    @feedback = Feedback.find(params[:id])
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(params[:feedback])

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to feedbacks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= semantic_form_for @feedback do |f| %>
  <%= f.inputs %>

  <%= f.actions %>

<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing feedback</h1>

<%= render 'form' %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/index.html.erb
<h1>Listing feedbacks</h1>

<table class="table table-striped">
  <tr>
    <th>Comment</th>
    <th>Rate</th>
    <th>Booking</th>
    <th>Actions</th>
  </tr>

<% @feedbacks.each do |feedback| %>
  <tr>
    <td><%= feedback.comment %></td>
    <td><%= feedback.raiting %>/5</td>
    <td><%= feedback.booking.user.name %></td>
    <td><%= link_to 'Show', feedback,:class => "btn btn-success" %> <%= link_to 'Edit', edit_feedback_path(feedback),:class => "btn btn-warning" %> <%= link_to 'Delete', feedback, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Feedback', new_feedback_path,:class => "btn btn-primary" %>

app/views/feedbacks/new.html.erb
<h1>New feedback</h1>

<%= render 'form' %>

<%= link_to 'Back', feedbacks_path,:class => "btn" %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>