config/routes.rb
require 'api_constraints'
ParkNGo::Application.routes.draw do

  resources :services


  resources :prices


  resources :transactions


  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
        resources :bookings
        resources :feedbacks
        resources :parking_types
        resources :parkings
        resources :parking_companies
        resources :parking_branches
        resources :cars
    end
  end

  resources :cars


  match '/bookings/current', to: 'bookings#current', :as => "current_bookings"

  # get "parking_companies/new"
  match '/company/add', to: 'parking_companies#new', :as => "add_parking_company"
  # get "parking_branch/new"
  match '/company/branch/add', to: 'parking_branches#new', :as => "add_parking_branch"
   # get "parking_branch/show"
  match '/company/branch/:id', to: 'parking_branches#show', :as => "show_company_branch"
    # get "edit_parking_company" => parking_companies#edit custom route edit_parking_company_path
  match '/company/edit/:id', to: 'parking_companies#edit', :as => "edit_parking_company"
  # get "parking_companies/index" custom route all_companies_path 
  match '/company', to: 'parking_companies#index', :as => "all_companies" 

  match '/company/show' => redirect('/company')
  # match '/parking_companies' => redirect('/company')


  # branch_by_airport_path(:airport)
  match '/airport/:airport', to: 'parking_branches#index', :as => "branch_by_airport" 

  get "parking_companies/destroy"

  get "parking_branches/index"

  get "parking_branches/update"

  get "parking_branches/destroy"


  # get "parking_companies/show" custom route show_company_path

  match '/company/show/:company_name', to: 'parking_companies#show', :as => "show_company"
  # match '/parking_companies/:id' => redirect('/company/show/%{id}')
  # match '/company/show/:id', to: 'parking_companies#show', :as => "show_company_by_id"
  match '/company/branch' => redirect('/company')
  match '/company/:company_name', to: 'parking_companies#index', :as => "company_by_name" 
  
  # get "parking_companies/update"
  # match '/company/update', to: 'parking_companies#update', :as => ""





 
  


  #pass the id to path edit_parking_branch_path(id)
  match '/company/branch/edit/:id', to: 'parking_branches#edit', :as => "edit_parking_branch"
  



  authenticated :user do
    root :to => 'home#index'
    
  end
  root :to => "home#index"

  devise_for :users, :path_names => { :sign_up => "register" }, :path_names => { :sign_in => "login" }
  resources :users do
    resources :addreses
  end

  resources :bookings


  resources :feedbacks


  resources :parking_types


  resources :parkings
  resources :parking_companies
  resources :parking_branches




end

app/models/car.rb
class Car < ActiveRecord::Base
  attr_accessible  :user_id, :car_colour, :car_last_state_report, :car_make, :car_milage, :car_model, :car_picture, :car_year
  belongs_to :user
  has_many :bookings
end

app/controllers/api/v1/cars_controller.rb
module Api
  module V1
    class CarsController < ApplicationController

      respond_to :json, :xml
      def index
        @cars = Car.all

      end

      def show
        @car = Car.find(params[:id])

      end


      def new
        @car = Car.new

      end


      def edit
        @car = Car.find(params[:id])
      end

      # POST /cars
      # POST /cars.json
      def create
        @car = Car.new(params[:car])


          if @car.save
            redirect_to @car, notice: 'Car was successfully created.'

          else
            render action: "new"

          end

      end

      # PUT /cars/1
      # PUT /cars/1.json
      def update
        @car = Car.find(params[:id])


          if @car.update_attributes(params[:car])
            redirect_to @car, notice: 'Car was successfully updated.'

          else
            render action: "edit"

          end

      end

      # DELETE /cars/1
      # DELETE /cars/1.json
      def destroy
        @car = Car.find(params[:id])
        @car.destroy
          redirect_to cars_url
      end
    end
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :authenticate_user!
  respond_to :json, :xml
  def index
    @cars = Car.all

  end

  def show
    @car = Car.find(params[:id])

  end


  def new
    @car = Car.new

  end


  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(params[:car])


      if @car.save
        redirect_to @car, notice: 'Car was successfully created.'

      else
        render action: "new"

      end

  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    @car = Car.find(params[:id])


      if @car.update_attributes(params[:car])
        redirect_to @car, notice: 'Car was successfully updated.'

      else
        render action: "edit"

      end

  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy
      redirect_to cars_url
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<%= semantic_form_for @car do |f| %>
	<%= f.semantic_errors %>
  <%= f.inputs do %>
  <%= f.input :user_id, :as => :select, :collection => Hash[User.all.map {|c| [c.name,c.id]}], :required => true %>
  <%= f.input :car_make %>
  <%= f.input :car_model %>
  <%= f.input :car_colour %>
  <%= f.input :car_year %>
  <%= f.input :car_milage %>
  <%= f.input :car_picture %>
  <%= f.input :car_last_state_report %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<h1>Listing cars</h1>

<table class="table table-striped">
  <tr>
    <th>Owner</th>
    <th>Make</th>
    <th>Model</th>
    <th>Colour</th>
    <th>Year</th>
    <th>Milage</th>
    <th>Picture</th>
    <th>Last state report</th>
    <th>Actions</th>
  </tr>

<% @cars.each do |car| %>
  <tr>
    <td><%= car.user.name %></td>
    <td><%= car.car_make %></td>
    <td><%= car.car_model %></td>
    <td><%= car.car_colour %></td>
    <td><%= car.car_year %></td>
    <td><%= car.car_milage %></td>
    <td><%= car.car_picture %></td>
    <td><%= car.car_last_state_report %></td>
    <td><%= link_to 'Show', car, :class => "btn btn-success" %> <%= link_to 'Edit', edit_car_path(car), :class => "btn btn-warning" %> <%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Car', new_car_path, :class => "btn btn-primary" %>

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>